language: android
jdk: oraclejdk8
# Turn off caching to avoid any caching problems
cache: false
android:

        components:
                - platform-tools
                - build-tools-25.0.0
                - android-25
                - extra-android-m2repository
                - extra-google-m2repository
script:
        - ./gradlew build
